#!/bin/bash

#$ -M YOUR EMAIL ADDRESS
#$ -m n
#$ -pe mpi-16 64
#$ -q *@@richter
#$ -N tutorial
#$ -j y

case=case1
time=0000000
runout=$case.out.$time

datadir=/scratch365/YOUR_NDID/tutorial/$case
homedir=~/tutorial/$case

cd $homedir

module load mvapich2
module load intel

imachine=0
echo $imachine > ./mach.file
echo $datadir >> ./mach.file

mpirun -n 64 $homedir/../lesmpi.a $homedir/params.in > $datadir/$runout


