#!/bin/bash

group_storage=/afs/crc.nd.edu/group/RichterLab

#$ -M agrace4@nd.edu
#$ -m n
#$ -pe mpi-16 64
#$ -q *@@richter
#$ -N slip_stat
#$ -j y

case=NTLP
time=0000000
runout=$case.out.$time

datadir=/scratch365/agrace4/$case
homedir=~/$case/test_cases/channel

# create the directory for the output.
# mkdir -p $datadir

cd $homedir

module load mvapich2
module load intel
##module load intelmpi
module load netcdf

imachine=0
echo $imachine > ./mach.file
echo $datadir >> ./mach.file

mpirun -n 64 $homedir/../../lesmpi.a $homedir/params.in > $datadir/$runout
